### ISSUE TITLE
Migration from 0.0.5 to 1.0.x?

### ISSUE THREAD

**Issue by TLINDEN** [olekukonko/tablewriter#244]
Hi,

could you please provide some kind of guide how to migrate from 0.0.5 to 1.0.x? When upgrading to 1.0.2 I get:

```default
lib/printer.go:82:9: table.SetHeader undefined (type *tablewriter.Table has no field or method SetHeader)
lib/printer.go:85:8: table.SetAutoWrapText undefined (type *tablewriter.Table has no field or method SetAutoWrapText)
lib/printer.go:87:8: table.AppendBulk undefined (type *tablewriter.Table has no field or method AppendBulk)
lib/printer.go:118:8: table.SetBorders undefined (type *tablewriter.Table has no field or method SetBorders)
lib/printer.go:118:31: undefined: tablewriter.Border
lib/printer.go:119:8: table.SetCenterSeparator undefined (type *tablewriter.Table has no field or method SetCenterSeparator)
lib/printer.go:120:8: table.SetAutoWrapText undefined (type *tablewriter.Table has no field or method SetAutoWrapText)
lib/printer.go:123:9: table.SetHeader undefined (type *tablewriter.Table has no field or method SetHeader)
lib/printer.go:126:8: table.AppendBulk undefined (type *tablewriter.Table has no field or method AppendBulk)
lib/printer.go:140:9: table.SetHeader undefined (type *tablewriter.Table has no field or method SetHeader)
lib/printer.go:140:9: too many errors
make: *** [Makefile:53: buildlocal] Error 1
```

Thanks a lot!

**Comment by TLINDEN** [comment]
I tried my luck, but failed.

So far I have this:
```go
	table := tablewriter.NewTable(tableString,
		tablewriter.WithRenderer(
			renderer.NewBlueprint(tw.RendererConfig{
				Borders: tw.BorderNone,
				Symbols: tw.NewSymbols(tw.StyleASCII),
				Settings: tw.Settings{
					Separators: tw.Separators{BetweenRows: tw.On},
					Lines:      tw.Lines{ShowFooterLine: tw.On},
				},
			})),
		tablewriter.WithConfig(tablewriter.Config{
			Row: tw.CellConfig{
				Formatting: tw.CellFormatting{
					AutoWrap:  tw.WrapNone,
					Alignment: tw.AlignLeft,
				},
				Padding: tw.CellPadding{
					Global: tw.Padding{Left: "", Right: pad},
				},
			},
		}),
	)
```

Doesn't compile:
```default
lib/printer.go:168:29: undefined: tw.RendererConfig
```

The only structure which matches would be `Rendition`, so I tried this. It compiles but crashes:

```default
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/olekukonko/tablewriter/renderer.(*Blueprint).formatCell(0xc0000cc120, {0xc000014b78, 0x1}, 0x5, {{0x0, 0x0}, {0x8c3608, 0x1}, {0x0, 0x0}, ...}, ...)
        /home/scip/go/pkg/mod/github.com/olekukonko/tablewriter@v1.0.2/renderer/blueprint.go:261 +0x2475
github.com/olekukonko/tablewriter/renderer.(*Blueprint).renderLine(0xc0000cc120, {0x8c73a8, 0xc000080720}, {{{0x81e848, 0x3}, {0x81fa9b, 0x6}, 0xc000204840, 0xc000204870, 0xc0002048a0, ...}, ...})
        /home/scip/go/pkg/mod/github.com/olekukonko/tablewriter@v1.0.2/renderer/blueprint.go:507 +0x112c
github.com/olekukonko/tablewriter/renderer.(*Blueprint).Row(0xc0000cc120, {0x8c73a8, 0xc000080720}, {0x0?, 0x76?, 0xc0000342f8?}, {{{0x81e848, 0x3}, {0x81fa9b, 0x6}, ...}, ...})
        /home/scip/go/pkg/mod/github.com/olekukonko/tablewriter@v1.0.2/renderer/blueprint.go:194 +0x190
github.com/olekukonko/tablewriter.(*Table).renderLine(0xc0001fc008, 0xc0000c3b00, 0x8c3608?, 0xc000034778, 0x0?, 0x0?)
        /home/scip/go/pkg/mod/github.com/olekukonko/tablewriter@v1.0.2/tablewriter.go:1589 +0x5ed
github.com/olekukonko/tablewriter.(*Table).renderRow(0xc0001fc008, 0xc0000c3b00, 0xc000204180)
        /home/scip/go/pkg/mod/github.com/olekukonko/tablewriter@v1.0.2/tablewriter.go:1698 +0xc93
github.com/olekukonko/tablewriter.(*Table).render(0xc0001fc008)
        /home/scip/go/pkg/mod/github.com/olekukonko/tablewriter@v1.0.2/tablewriter.go:315 +0x2e4
github.com/olekukonko/tablewriter.(*Table).Render(...)
        /home/scip/go/pkg/mod/github.com/olekukonko/tablewriter@v1.0.2/tablewriter.go:275
github.com/tlinden/tablizer/lib.printASCIIData({_, _}, {0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
        /home/scip/dev/tablizer/lib/printer.go:214 +0x1dd
github.com/tlinden/tablizer/lib.printData({_, _}, {0x0, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...)
        /home/scip/dev/tablizer/lib/printer.go:56 +0x3bb
github.com/tlinden/tablizer/lib.ProcessFiles(0xc0001ba788, {0xb6c880?, 0x0?, 0x0?})
        /home/scip/dev/tablizer/lib/io.go:61 +0x287
github.com/tlinden/tablizer/cmd.Execute.func1(0xc0000b6600?, {0xb6c880, 0x0, 0x0})
        /home/scip/dev/tablizer/cmd/root.go:121 +0x267
github.com/spf13/cobra.(*Command).execute(0xc0001e4008, {0xc000016090, 0x0, 0x0})
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1019 +0xa7b
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e4008)
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1148 +0x40c
github.com/spf13/cobra.(*Command).Execute(...)
        /home/scip/go/pkg/mod/github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/tlinden/tablizer/cmd.Execute()
        /home/scip/dev/tablizer/cmd/root.go:205 +0xd65
main.Main(...)
        /home/scip/dev/tablizer/main.go:31
main.main()
        /home/scip/dev/tablizer/main.go:27 +0x13
```

Markdown-Rendering does not crash, but does not produce a Markdown table:

```default
| ONE | TWO |                                                                                                                                              
|:---:|:---:|                                                                                                                                              
| 1   | 4   |                                                                                                                                              
| 3   | 1   |                                                                                                                                              
| 5   | 2   |  
```
`:---:` doesn't look valid to me.

Please also note the huge amount of whitespace appended after each row.

**Comment by olekukonko** [comment]
#### Migration 

Sorry for the typo in the README. I will fix it immediately.

```go
package main

import (
	"github.com/olekukonko/tablewriter"
	"github.com/olekukonko/tablewriter/renderer"
	"github.com/olekukonko/tablewriter/tw"
	"os"
)

func main() {

	// using old example
	data := [][]string{
		{"A", "The Good", "500"},
		{"B", "The Very very Bad Man", "288"},
		{"C", "The Ugly", "120"},
		{"D", "The Gopher", "800"},
	}

	// simple exampl
	table := tablewriter.NewWriter(os.Stdout)

	// before
	// table.SetHeader([]string{"Name", "Sign", "Rating"})

	// now
	table.Header([]string{"Name", "Sign", "Rating"}). // or 
	table.Header("Name", "Sign", "Rating") // variadic. now supported 

	for _, v := range data {
		table.Append(v)
	}
	table.Render() // Send output

	// output
	//┌──────┬───────────────────────┬────────┐
	//│ NAME │         SIGN          │ RATING │
	//├──────┼───────────────────────┼────────┤
	//│ A    │ The Good              │ 500    │
	//│ B    │ The Very very Bad Man │ 288    │
	//│ C    │ The Ugly              │ 120    │
	//│ D    │ The Gopher            │ 800    │
	//└──────┴───────────────────────┴────────┘

	// more complex
	table = tablewriter.NewTable(os.Stdout,
		tablewriter.WithRenderer(
			renderer.NewBlueprint(tw.Rendition{ // this was a typo in the readme
				Borders: tw.BorderNone,
				Symbols: tw.NewSymbols(tw.StyleASCII),
				Settings: tw.Settings{
					Separators: tw.Separators{BetweenRows: tw.On},
					Lines:      tw.Lines{ShowFooterLine: tw.On},
				},
			})),
		tablewriter.WithConfig(tablewriter.Config{
			Row: tw.CellConfig{
				Formatting: tw.CellFormatting{
					AutoWrap:  tw.WrapNone,
					Alignment: tw.AlignLeft,
				},
				Padding: tw.CellPadding{
					Global: tw.Padding{Left: "", Right: "X"},
				},
			},
		}),
	)
	table.Header("Department", "Division", "Team", "Lead")
	table.Bulk(data)
	table.Render()

}
```

```
┌──────┬───────────────────────┬────────┐
│ NAME │         SIGN          │ RATING │
├──────┼───────────────────────┼────────┤
│ A    │ The Good              │ 500    │
│ B    │ The Very very Bad Man │ 288    │
│ C    │ The Ugly              │ 120    │
│ D    │ The Gopher            │ 800    │
└──────┴───────────────────────┴────────┘

```

```
 DEPARTMENT |       DIVISION       | TEAM | LEAD 
------------+----------------------+------+------
 AXXXXXXXXXX| The GoodXXXXXXXXXXXXX| 500XX| XXXXX
------------+----------------------+------+------
 BXXXXXXXXXX| The Very very Bad MaX| 288XX| XXXXX
------------+----------------------+------+------
 CXXXXXXXXXX| The UglyXXXXXXXXXXXXX| 120XX| XXXXX
------------+----------------------+------+------
 DXXXXXXXXXX| The GopherXXXXXXXXXXX| 800XX| XXXXX
------------+----------------------+------+------

```

#### Markdown
 
The **write space** is supposed to match the header width.
I see the problem with the **alignment**, will fix immediately 


Regarding the `|:---:|` part: this is a syntax used in Markdown tables to align text within the columns. Here's the breakdown:

* `|:---|` creates a standard, left-aligned column.
* `|:---:|` centers the text within the column.
* `|---:|` aligns the text to the right.

```go
package main

import (
	"github.com/olekukonko/tablewriter"
	"github.com/olekukonko/tablewriter/renderer"
	"os"
)

func main() {
	data := [][]int{
		{1, 4},
		{3, 1},
		{5, 2},
	}
	table := tablewriter.NewTable(os.Stdout, tablewriter.WithRenderer(renderer.NewMarkdown()))
	table.Header("ONE", "TWO")
	table.Bulk(data)
	table.Render() // Send output
}
```


In your table:

```
| ONE | TWO |
|:---:|:---:|
|  1  |  4  |
|  3  |  1  |
|  5  |  2  |
```

| ONE | TWO |
|:---:|:---:|
|  1  |  4  |
|  3  |  1  |
|  5  |  2  |



* The `:---:` means the contents of both "ONE" and "TWO" columns will be centered. so the actual result should have been

**Comment by olekukonko** [comment]
please use  `go get -u -v github.com/olekukonko/tablewriter@ca4dd0493d51bbf4c06258df807a5adb4ce9fca1` test and let me know this is working fine so that i can create a new tag.

**Comment by olekukonko** [comment]
Use https://github.com/olekukonko/tablewriter/tree/experiment  test and revert

**Comment by alexandear** [comment]
I'm encountering a similar issue and am trying to migrate [the following function](https://github.com/mgechev/revive/blob/f6cc22de4d5c75cf471501affa5522c778078761/formatter/friendly.go#L131-L141) from v0.0.5:

```go
func (*Friendly) table(rows [][]string) string {
	buf := new(bytes.Buffer)
	table := tablewriter.NewWriter(buf)
	table.SetBorder(false)
	table.SetColumnSeparator("")
	table.SetRowSeparator("")
	table.SetAutoWrapText(false)
	table.AppendBulk(rows)
	table.Render()
	return buf.String()
}
```

@olekukonko, does the following look correct?

```go
func (*Friendly) table(rows [][]string) string {
	buf := new(bytes.Buffer)
	table := tablewriter.NewTable(buf,
		tablewriter.WithRenderer(
			renderer.NewBlueprint(tw.Rendition{
				Borders: tw.BorderNone,
				Symbols: &tw.SymbolNothing{},
			})),
	)
	table.Bulk(rows)
	table.Render()
	return buf.String()
}
```

**Comment by TLINDEN** [comment]
Ok, looks much better, compiles and no more crashes. Markdown output has no excess spaces anymore. But ascii tables still have lines, although I disabled them:

```golang
	table := tablewriter.NewTable(tableString,
		tablewriter.WithRenderer(
			renderer.NewBlueprint(tw.Rendition{
				Borders: tw.BorderNone,
				Symbols: tw.NewSymbols(tw.StyleASCII),
				Settings: tw.Settings{
					Separators: tw.Separators{BetweenRows: tw.Off},
					Lines:      tw.Lines{ShowFooterLine: tw.Off},
				},
			})),
		tablewriter.WithConfig(tablewriter.Config{
			Row: tw.CellConfig{
				Formatting: tw.CellFormatting{
					AutoWrap:  tw.WrapNone,
					Alignment: tw.AlignLeft,
				},
				Padding: tw.CellPadding{
					Global: tw.Padding{Left: "", Right: pad},
				},
			},
		}),
	)
```

Output:
```default
 ONE | TWO 
-----+-----
 1                         | 4                     
 3                         | 1                     
 5                         | 2  
```

As you can see, there are excess spaces again, excess spaces in column 1 and the are bars. I'd need this instead:

```default
ONE     TWO 
1       4  
3       1  
5       2 
```

best,
Tom

**Comment by TLINDEN** [comment]
Ok, I added 2 more flags:

```golang
[..]
Separators: tw.Separators{BetweenRows: tw.Off, BetweenColumns: tw.Off},
Lines:      tw.Lines{ShowFooterLine: tw.Off, ShowHeaderLine: tw.Off},
```
Now it's looking like this:

```default
 ONE  TWO 
 1                          4                      
 3                          1                      
 5                          2  
```

But excess spaces are still there, also there are now leading spaces.

**Comment by olekukonko** [comment]
Am unable to replicate this see: 

- https://goplay.tools/snippet/o0n0KnaJ7dh 
- https://go.dev/play/p/_eAauuUgz6R


```
 ONE | TWO 
-----+-----
 1***| 4***
 3***| 1***
 5***| 2***
```

**Comment by TLINDEN** [comment]
I have enabled debug, but there's no additional output.

However, the padding problem is caused by this:

```golang
pad = "\t"
[..]
Padding: tw.CellPadding{
	Global: tw.Padding{Left: "", Right: pad},
},
```
So, that's obviously wrong. But I'd need a replacement for the old `table.SetTablePadding("\t")`. 

With 0.0.5 the padding looked like this (output of `cat -T`) when using TAB for padding (which was wrong as well, since the space+tabs after the last column is not needed):

```default
ONE^ITWO 
1  ^I4  ^I
3  ^I1  ^I
5  ^I2  ^I
```

Now, it looks like this:

```default
 ONE  TWO 
 1^I^I^I    4^I^I^I   
 3^I^I^I    1^I^I^I   
 5^I^I^I    2^I^I^I
```

What I really need is ONE tab between columns so that the output is valid TSV.

But your example code on goplay still has the leading spaces, although left padding is set to the empty string.

**Comment by olekukonko** [comment]
```go
package main

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/olekukonko/tablewriter"
	"github.com/olekukonko/tablewriter/renderer"
	"github.com/olekukonko/tablewriter/tw"
)

func main() {
	data := [][]string{
		{"left", "\tright"},
		{"bob", "\talice"},
	}
	tableString := &strings.Builder{}
	table := tablewriter.NewTable(tableString,
		tablewriter.WithRenderer(
			renderer.NewBlueprint(tw.Rendition{
				Borders: tw.BorderNone,
				Symbols: tw.NewSymbols(tw.StyleASCII),
				Settings: tw.Settings{
					Separators: tw.Separators{BetweenRows: tw.Off, BetweenColumns: tw.Off},
					Lines:      tw.Lines{ShowFooterLine: tw.Off, ShowHeaderLine: tw.Off},
				},
			})),
		tablewriter.WithConfig(tablewriter.Config{
			Header: tw.CellConfig{
				Formatting: tw.CellFormatting{
					AutoFormat: tw.Off,
				},
				Padding: tw.CellPadding{
					Global: tw.Padding{Left: "", Right: ""},
				},
			},
			Row: tw.CellConfig{
				Formatting: tw.CellFormatting{
					AutoWrap:  tw.WrapNone,
					Alignment: tw.AlignLeft,
				},
				Padding: tw.CellPadding{
					Global: tw.Padding{Left: "", Right: ""},
				},
			},
		}),
	)

	table.Header("ONE", "\tTWO")
	table.Bulk(data)
	table.Render()

	r := regexp.MustCompile(`\t`)
	fmt.Println(r.ReplaceAllString(tableString.String(), "TAB"))
}
```

```
 ONE    TABTWO  
 left  TABright 
 bob   TABalice 

```

This should fix your tab issue when i merge

**Comment by olekukonko** [comment]
```
package main

import (
	"os"

	"github.com/olekukonko/tablewriter"
	"github.com/olekukonko/tablewriter/tw"
)

func main() {
	data := [][]string{
		{"node1.example.com", "Ready", "compute", "1.11"},
		{"node2.example.com", "Ready", "compute", "1.11"},
		{"node3.example.com", "Ready", "compute", "1.11"},
		{"node4.example.com", "NotReady", "compute", "1.11"},
	}

	table := tablewriter.NewTable(os.Stdout,

		// Set general configuration
		tablewriter.WithConfig(
			tablewriter.Config{
				Header: tw.CellConfig{
					Formatting: tw.CellFormatting{
						AutoFormat: tw.Off, // Switched off
					},
				},
			},
		),
	)
	table.Header("header1`", "HeaDEr2", "header 3", "HEADER4")
	table.Bulk(data)
	table.Render()
}

```


```
┌───────────────────┬──────────┬──────────┬─────────┐
│     header1`      │ HeaDEr2  │ header 3 │ HEADER4 │
├───────────────────┼──────────┼──────────┼─────────┤
│ node1.example.com │ Ready    │ compute  │ 1.11    │
│ node2.example.com │ Ready    │ compute  │ 1.11    │
│ node3.example.com │ Ready    │ compute  │ 1.11    │
│ node4.example.com │ NotReady │ compute  │ 1.11    │
└───────────────────┴──────────┴──────────┴─────────┘

```


Since you're using AutoFormat: false, I assume you're on version v1.0.5. Will proceed with v1.0.6 soon. I had been hesitant due to this issue: https://github.com/olekukonko/tablewriter/issues/261.

The problem is that formatting has three states: default, explicitly on, and explicitly off,  something a simple boolean can't represent properly. This limitation has caused issues. The only viable solution was to change the formatting flag from a boolean to an enum-like state, which I’ve already implemented. However, I was concerned about the potential for breaking changes.

According to the migration guide, community help would be valuable  but so far, no one has stepped in. To date, the migration has involved 21,012 insertions and 3,729 deletions, and maintaining backward compatibility (especially for output) has been the most challenging part.

If you're interested in helping out, that would be greatly appreciated — I’d be happy to collaborate.

**Comment by olekukonko** [comment]
Work in progress https://github.com/olekukonko/tablewriter/blob/master/MIGRATION.md

**Comment by TLINDEN** [comment]
Sorry, but there's still an issue with the leading spaces. Sure, I can just iterate over the output and remove them myself. But this would really get beyond the scope, it would be easier to just write the table printing code myself.

So, using v1.0.6 I get:

```default
 ONE    TWO 
 1      4   
 3      1   
 5      2
^-- leading space
```

**Comment by per1234** [comment]
>there's still an issue with the leading spaces

> there's a trailing space appended as well.

These are the result of the "cushion" leading and trailing space that is added to each cell value by default. The leading space that is bothering you is the left cushion on the first column's cells. The trailing space that is bothering you is the right cushion on the last column's cells.

The ability to disable the addition of the "cushion" has been added. This is done by adding the `tablewriter.WithPadding(tw.PaddingNone)` option argument to the `tablewriter.NewTable` call.

I shared a program that demonstrates that here:

https://github.com/olekukonko/tablewriter/issues/260#issuecomment-2892505143

**Comment by olekukonko** [comment]
```go
// Padding defines the spacing characters around cell content in all four directions.
// A zero-value Padding struct will use the table's default padding unless Overwrite is true.
type Padding struct {
	Left   string
	Right  string
	Top    string
	Bottom string

	// Overwrite forces tablewriter to use this padding configuration exactly as specified,
	// even when empty. When false (default), empty Padding fields will inherit defaults.
	//
	// For explicit no-padding, use the PaddingNone constant instead of setting Overwrite.
	Overwrite bool
}
```

Since you are using empty space ...  ` tw.PaddingNone,`  or `Global: tw.Padding{Left: "", Right: "", Overwrite: true},`
